const express = require('express');
const userService = require('../services/users');
const cookieParser = require('cookie-parser');

const router = express.Router();

router.get('/', function(req, res, next) {
  // List all users - NO AUTH AT PRESENT
  let db = req.app.get('super6db');
  let collection = db.collection('users');
  let items = collection.find({}).toArray(function (err, docs) {
    if (err) {
      console.error(err)
    }
    res.json(docs)
  });
});

router.post('/', function (req, res, next) {
  // Save a user - NO AUTH AT PRESENT
  let email = req.body.email;
  let password = req.body.password;
  let userId = userService.createUser(req.app.get('super6db'), email, password, false, function (error, result) {
    res.json(result.ops[0]);
  }, function() {
    res.statusCode = 500;
    res.send('Error adding user');
  });

});

router.post('/login/', function(req, res, next){
    let email = req.body.email;
    let password = req.body.password;
    if(email === 'user@gmail.com' && password === 'password'){ // to be replaced with call to the user service
        res.cookie('super6token', 'abcd1234', {maxAge: 3600000}); // to be replaced with the session token generated by the service
        res.redirect('../');
    } else {
        res.send('Incorrect details');
    }
});

router.get('/logout', function (req, res, next) {
    // Delete token from database via user service
    res.clearCookie('super6token');
    res.redirect('../');
});

module.exports = router;
