const express = require('express');
const userService = require('../services/users');
const cookieParser = require('cookie-parser');

const signUpService = require('../services/signup') // CS CODE !!!!
const userProfileService = require('../services/profile') // CS CODE !!!!!!!!

const router = express.Router();

router.get('/', function (req, res, next) {
    // List all users - NO AUTH AT PRESENT (only for admin)
    const db = req.app.get('super6db');
    userService.list(db).then((users) => {
        res.json(users)
    });
});


router.post('/signup', function (req, res, next) {
    // Save a user - NO AUTH AT PRESENT
    const email = req.body.email;
    const password = req.body.password;
    signUpService.makeUser(email, passowrd);
});

router.post('/login/', function (req, res, next) {
    const email = req.body.email;
    const password = req.body.password;

    // needs to vberify the users in the DB (do it via a service)
    if (email === 'user@gmail.com' && password === 'password') { // to be replaced with call to the user service
        res.cookie('super6token', 'abcd1234', {
            maxAge: 3600000
        }); // to be replaced with the session token generated by the service
        res.redirect('../');
    } else {
        res.send('Incorrect details');
    }
});

router.get('/logout', function (req, res, next) {
    // Delete token from database via user service
    res.clearCookie('super6token');
    res.redirect('../');
});


module.exports = router;